File Name: ML-22Feb-Class-Assignment-2
Author   : Utpal Shanbhag
Date     : 14-April-2020

Task-1:1 - Problem Statement

Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
#Solution for Task-1:1:

def compute_div():
    try:
        result = 5/0
        print("Result:",result)
    except ArithmeticError:
        print ("There is an Arithmetic Exception Error.")
    except:
        print("There is an exception due to other than ArithmeticError")

compute_div()

There is an Arithmetic Exception Error.


Task-1:2 - Problem Statement

Implement a Python program to generate all sentences where 
subject is in ["Americans","Indians"] 
verb is in ["Play", "watch"] 
object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [2]:
#Solution for Task-1:2:

subject_list=["Americans","Indians"]
verb_list   =["play","watch"]
object_list =["Baseball","Cricket"]

#form sentences with combination of all the above 3 lists
sentence_list = [(subject + " " + verb + " " + objects) for subject in subject_list for verb in verb_list for objects in object_list]

print("Output of the program is:\n")
for sentence in sentence_list:
    print (sentence + ".")

Output of the program is:

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


Task-2:1- Problem Statement

Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [3]:
#Solution for Task-2:1:

#generateVander function to populate geometric progression matrix

def generateVander(inp_array, no_of_cols):
    import numpy as np
    result=np.vander(inp_array,no_of_cols,increasing = False)
    return result

def main_func():
    input_string     = input("Please enter the list of input integers seperated by comma: ")
    input_no_of_cols = input("Please enter the no of columns in Output matrix: ")
    
    input_list = input_string.split(",")
    length_input_list = len(input_list)
        
    for i in range(0,length_input_list): 
        input_list[i] = int(input_list[i])
    
    input_no_of_cols = int(input_no_of_cols)
    
    print("\nResult of vander function is:\n\n",generateVander(input_list, input_no_of_cols))
    
main_func()

Please enter the list of input integers seperated by comma: 1,2,3,4,5,6
Please enter the no of columns in Output matrix: 6

Result of vander function is:

 [[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]
